matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required

language: c++
before_install:
#  - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then openssl aes-256-cbc -K $encrypted_8b763c087de9_key -iv $encrypted_8b763c087de9_iv -in pxscene-build.pem.enc -out /tmp/pxscene-build.pem -d; fi
#  - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then  eval "$(ssh-agent -s)"; fi
#  - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then  chmod 0600 /tmp/pxscene-build.pem; fi
#  - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then  ssh-add /tmp/pxscene-build.pem; fi
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - ./ci/before_install.sh
#  - if [ "$TRAVIS_EVENT_TYPE" != "cron" ] && {[ "$TRAVIS_EVENT_TYPE" = "push" ] || [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]}; then export PATH=/usr/local/opt/ccache/libexec:$PATH; fi
# NOTE THAT COVERITY IS COMPATIBLE WITH gcc 7; upload to coverity fails when using gcc 6 
#  - if [ "$TRAVIS_EVENT_TYPE" != "cron" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then  export CC=/usr/bin/gcc-6; export CXX=/usr/bin/g++-6 ; sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc ; sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++ ; fi
#  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
#  - gcc -v && g++ -v 


install:
  - if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then ./ci/install.sh; fi
before_script:
  - if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then ./ci/before_script.sh; fi
script:
  - if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then ./ci/clean_coverity.sh; fi

addons:
  coverity_scan:
    project:
      name: "conniefry/pxCore"
      description: "Build submitted via Travis CI"
    notification_email: constance_fry@cable.comcast.com
    build_command_prepend: "echo build prepend"
    build_command:   "./ci/make_coverity.sh"
    branch_pattern: coverity_scan_2
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - gcc-6
#    - g++-6

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "N2ZtVvOUYbUu0cZCryr98qNyJU7gSPAIjcAaj1bT6CN/m94oP1Zn9d+RCY1kmShvA0+fX18gU9W4Rn6vGU0KeolIQl6Xnc1SdRVWZ5mDbgLyuZOFgkSU6MenfyqN5iSaVj82DacRTk1lUIKdYLbMy9zou5jWxhFjlq6hBqJfzcGAOJGDD67qHKCHJ8BZvc0mX94a02ENQLl0jQiHX00fVsnM2oRyNkdlckognhYEBJi9w4iCFMRWmY8+3RcskdNmyvu3mW1GrHRJZRuiHAAhXsPXJ9iSnEpjKxX8q9NfrmqjMvXRBBFzK2kA6WAmoCVwn2ZcVSncFcAQvtr6EMKLLg0vVXVpmRG6vHrl5qZnKsl44IBsXTx/0HSWb4RUIVYKztHCk39IalwjFst76MBGWc/J5oTz5cV8hJYFJID3L+mZLLGyQsaFpxL7yMNpw4q2nGY5JZ6nrSlg4sX0djCGTqxBfXP3aGKWyANWT2itFRB07V/TP9yzcwBjQPQAt3knnEzwkx/YZQZbr/sQNAC7KhsUyugNwOAcrl0R7lFNz9q/AmAaKNTnyGqrHa0+6ttrWPFtCBI32aTFziqlpET8tb1t+uUpvqSSg4l6qey6VrRBWgWGqFdeoot6Ut5fR2cGtcY94mEQT7iE9YBNoNe/ju2PCSR8+EUgKXegsAq0120="

